[build]
builder = "nixpacks"
buildCommand = "yarn install && yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3